# file: roles/common-hv/tasks/main.yml

---
- name: Update onapp-hv-install
  yum:
    name: onapp-hv-install
    state: latest

- name: Install expect utility
  yum:
    name: expect
    state: installed
  when: onapp_version > 6.1
